enable_resource: False
enable_calendar: False
num_pool_task_ratio: 2
num_pool_lower: 2
num_pool_upper: 4
num_agent_lower: 1
num_agent_upper: 2
task_duration_dist: "norm"
task_duration_mean_dist: "uniform"
task_duration_mean_loc: 60
task_duration_mean_scale: 120
task_duration_std_dist: "uniform"
task_duration_std_loc: 5
task_duration_std_scale: 15
arrival_rate_dist: "constant"
arrival_rate_loc: 0.5
arrival_rate_scale: 0
sim_interval_dist: "uniform_const"
sim_interval_loc: 30
sim_interval_scale: 120
sim_time_unit: "m"